// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CNProjetos.Client.Models
{
    public partial class codpostal
    {
        public codpostal()
        {
            cliente = new HashSet<cliente>();
        }

        public int codpostalId { get; set; }
        public int distrito_Id { get; set; }
        public int concelho_Numero { get; set; }
        public string concelho_Codigo { get; set; }
        public int concelho_Id { get; set; }

        public virtual concelho concelho { get; set; }
        public virtual distrito distrito { get; set; }
        public virtual ICollection<cliente> cliente { get; set; }
    }
}