// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CNProjetos.Client.Models
{
    public partial class distrito
    {
        public distrito()
        {
            cliente = new HashSet<cliente>();
            codpostal = new HashSet<codpostal>();
            concelho = new HashSet<concelho>();
        }

        public int distritoId { get; set; }
        public string distritoNome { get; set; }

        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<codpostal> codpostal { get; set; }
        public virtual ICollection<concelho> concelho { get; set; }
    }
}