// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CNProjetos.Client.Models
{
    public partial class estadoprojeto
    {
        public estadoprojeto()
        {
            projeto = new HashSet<projeto>();
        }

        public int estadoprojetoId { get; set; }
        public string estadoprojetoNome { get; set; }

        public virtual ICollection<projeto> projeto { get; set; }
    }
}