// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CNProjetos.Client.Models
{
    public partial class projeto
    {
        public int projetoId { get; set; }
        public string projetoNumero { get; set; }
        public string projetoDesignacao { get; set; }
        public decimal? projetoValoraprovado { get; set; }
        public decimal? projetoIncentivoaprovado { get; set; }
        public decimal? projetoValorrealizado { get; set; }
        public decimal? projetoIncentivorecebido { get; set; }
        public DateTime? projetoDatasubmissao { get; set; }
        public DateTime? projetoDatadecisao { get; set; }
        public DateTime? projetoDatacontratacao { get; set; }
        public DateTime? projetoDatainicio { get; set; }
        public DateTime? projetoDatafim { get; set; }
        public string projetoResponsavel { get; set; }
        public int cliente_Id { get; set; }
        public int medida_Id { get; set; }
        public int estado_Id { get; set; }

        public virtual cliente cliente { get; set; }
        public virtual estadoprojeto estado { get; set; }
        public virtual medida medida { get; set; }
    }
}