// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CNProjetos.Client.Models
{
    public partial class setor
    {
        public setor()
        {
            cliente = new HashSet<cliente>();
        }

        public int setorId { get; set; }
        public string setorNome { get; set; }

        public virtual ICollection<cliente> cliente { get; set; }
    }
}