// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace CNProjetos.Client.Models
{
    public partial class utilizador
    {
        public int utilizadorId { get; set; }
        public string utilizadorEmail { get; set; }
        public string utilizadorIniciais { get; set; }
        public string utilizadorNome { get; set; }
    }
}